# Generated by Django 3.2.19 on 2024-02-03 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionText', models.TextField(primary_key=True, serialize=False, verbose_name='Question')),
                ('questionOption1', models.TextField(verbose_name='Option 1')),
                ('questionOption2', models.TextField(verbose_name='Option 2')),
                ('questionOption3', models.TextField(verbose_name='Option 3')),
                ('questionOption4', models.TextField(verbose_name='Option 4')),
                ('correctOption', models.TextField(verbose_name='Correct answer')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testName', models.TextField(primary_key=True, serialize=False, verbose_name='Test name')),
                ('date', models.DateTimeField(verbose_name='Available from')),
                ('question1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q1', to='DAWActivity.question')),
                ('question10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q10', to='DAWActivity.question')),
                ('question2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q2', to='DAWActivity.question')),
                ('question3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q3', to='DAWActivity.question')),
                ('question4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q4', to='DAWActivity.question')),
                ('question5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q5', to='DAWActivity.question')),
                ('question6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q6', to='DAWActivity.question')),
                ('question7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q7', to='DAWActivity.question')),
                ('question8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q8', to='DAWActivity.question')),
                ('question9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q9', to='DAWActivity.question')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('villageName', models.TextField(primary_key=True, serialize=False, verbose_name='Village Name')),
                ('dailyFood', models.IntegerField(verbose_name='Daily food obtained')),
                ('dailyWood', models.IntegerField(verbose_name='Daily wood obtained')),
                ('dailyStone', models.IntegerField(verbose_name='Daily stone obtained')),
                ('storedFood', models.IntegerField(verbose_name='Total food stored')),
                ('storedWood', models.IntegerField(verbose_name='Total wood stored')),
                ('storedStone', models.IntegerField(verbose_name='Total stone stored')),
                ('foodLevel', models.IntegerField(verbose_name='Food level')),
                ('woodLevel', models.IntegerField(verbose_name='Wood level')),
                ('stoneLevel', models.IntegerField(verbose_name='Stone level')),
                ('wallLevel', models.IntegerField(verbose_name='Walls level')),
                ('storageLevel', models.IntegerField(verbose_name='Storage level')),
                ('soldiers', models.IntegerField(verbose_name='Amount of units')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.IntegerField(verbose_name='Building')),
                ('woodCost', models.IntegerField(verbose_name='WoodCost')),
                ('stoneCost', models.IntegerField(verbose_name='StoneCost')),
                ('completed', models.BooleanField(verbose_name='Completed')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAWActivity.village')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(verbose_name='Units')),
                ('foodCost', models.IntegerField(verbose_name='FoodCost')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAWActivity.village')),
            ],
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wants', models.IntegerField(verbose_name='Wanted amount')),
                ('wantsResource', models.TextField(verbose_name='Wanted resource')),
                ('offers', models.IntegerField(verbose_name='Offered amount')),
                ('offersResource', models.TextField(verbose_name='Offered resource')),
                ('accepted', models.BooleanField(verbose_name='Offering accepted')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destination', to='DAWActivity.village')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Source', to='DAWActivity.village')),
            ],
        ),
        migrations.CreateModel(
            name='TestResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Points obtained')),
                ('testName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAWActivity.test')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usedSoldiers', models.IntegerField(verbose_name='Soldiers')),
                ('registeredDateTime', models.DateTimeField(verbose_name='Registration date')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attacker', to='DAWActivity.village')),
                ('defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Defendant', to='DAWActivity.village')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityText', models.TextField(verbose_name='Activity description')),
                ('activityDate', models.DateField(verbose_name='Time registered')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAWActivity.village')),
            ],
        ),
    ]
