# Generated by Django 3.2.19 on 2024-02-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAWActivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='completed',
            field=models.BooleanField(default=None, verbose_name='Completed'),
            preserve_default=False,
        ),
    ]
