# Generated by Django 3.2.19 on 2024-02-03 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DAWActivity', '0002_training_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question10',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question6',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question7',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question8',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question9',
        ),
        migrations.AddField(
            model_name='question',
            name='testName',
            field=models.ForeignKey(default='Test1', on_delete=django.db.models.deletion.CASCADE, to='DAWActivity.test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='correctOption',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], default='a', max_length=1, verbose_name='Correct option'),
        ),
    ]
