# Generated by Django 3.2.12 on 2024-02-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAWActivity', '0004_auto_20240214_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
            preserve_default=False,
        ),
    ]
