# Generated by Django 3.2.12 on 2024-02-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DAWActivity', '0005_attack_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonusType', models.IntegerField(verbose_name='Bonus type')),
                ('bonusAmount', models.IntegerField(verbose_name='Bonus amount')),
                ('completed', models.BooleanField(verbose_name='Completed')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAWActivity.village')),
            ],
        ),
    ]
