# Generated by Django 3.2.19 on 2024-03-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAWActivity', '0007_auto_20240218_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('desc', models.TextField(verbose_name='Description')),
                ('newDate', models.DateTimeField(verbose_name='New date')),
            ],
        ),
    ]
