# Generated by Django 3.2.12 on 2024-08-15 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DAWActivity', '0008_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='lastLogin',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Last login'),
            preserve_default=False,
        ),
    ]
