# Generated by Django 3.2.12 on 2024-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAWActivity', '0011_alter_new_newdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='newDate',
            field=models.DateField(verbose_name='New date'),
        ),
    ]
