# Generated by Django 3.2.12 on 2024-08-15 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DAWActivity', '0012_alter_new_newdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastLogin',
        ),
        migrations.AddField(
            model_name='village',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='lastLogin',
            field=models.DateField(default=datetime.datetime(2024, 8, 15, 18, 7, 2, 727053, tzinfo=utc), verbose_name='Last login'),
            preserve_default=False,
        ),
    ]
