# Generated by Django 3.2.12 on 2024-09-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DAWActivity', '0013_auto_20240815_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('questionOptionText', models.TextField(primary_key=True, serialize=False, verbose_name='Option 1')),
                ('correctOption', models.BooleanField(verbose_name='Correct')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFill',
            fields=[
                ('questionText', models.TextField(primary_key=True, serialize=False, verbose_name='Question')),
                ('questionType', models.IntegerField(verbose_name='Type')),
                ('expectedText', models.TextField(verbose_name='Expected text')),
                ('testName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAWActivity.test')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('questionText', models.TextField(primary_key=True, serialize=False, verbose_name='Question')),
                ('questionType', models.IntegerField(verbose_name='Type')),
                ('testName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAWActivity.test')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='option',
            name='questionText',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAWActivity.questionoptions'),
        ),
    ]
