# Generated by Django 3.2.12 on 2024-09-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DAWActivity', '0014_auto_20240908_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionText', models.TextField(primary_key=True, serialize=False, verbose_name='Question')),
                ('expectedText', models.TextField(verbose_name='Expected text')),
                ('questionType', models.IntegerField(verbose_name='Type')),
                ('testName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAWActivity.test')),
            ],
        ),
        migrations.RemoveField(
            model_name='questionoptions',
            name='testName',
        ),
        migrations.DeleteModel(
            name='QuestionFill',
        ),
        migrations.AlterField(
            model_name='option',
            name='questionText',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAWActivity.question'),
        ),
        migrations.DeleteModel(
            name='QuestionOptions',
        ),
    ]
